### ISSUE TITLE
移动端图片保持宽高比采用padding-top 实现

### ISSUE THREAD

**Issue by pokerLife** [mHeartbeats/notes#52]
```css
.mod_banner {
    position: relative;
    padding-top: percentage(100/750); // 使用padding-top
    height: 0;
    overflow: hidden;
    img {
        width: 100%;
        height: auto;
        position: absolute;
        left: 0;
        top: 0; 
    }
}
```
